/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import cdz.Casa;
import cdz.Cavaleiro;

/**
 *
 * @author prestes
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    public void setIconCavaleiro(Cavaleiro cavaleiro){
        jLabel2.setLocation(225, 600);
        switch (cavaleiro.getNome()) {
            case "Shun":
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Shun.png")));
                break;
            case "Seiya":
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Seiya.png")));
                break;
            case "Ikki":
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ikki.png")));
                break;
            case "Shiryu":
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Shiryu.png")));
                break;
            case "Hyoga":
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Hyoga.png")));
            break;
        }
    }
    
    public void goIconCavaleiro(Casa casaAtual){
        switch (casaAtual.getNome()) {
            case "outside":
                jLabel2.setLocation(225, 600);
                break;
            case "corredorNorte":
                jLabel2.setLocation(225, 515);
                break;
            case "touro":
                jLabel2.setLocation(260, 390);
                break;
            case "aries":
                jLabel2.setLocation(225, 440);
                break;
            case "gemeos":
                jLabel2.setLocation(175, 360);
                break;
            case "cancer":
                jLabel2.setLocation(260, 328);
                break;
            case "leao":
                jLabel2.setLocation(190, 290);
                break; 
            case "virgem":
                jLabel2.setLocation(270, 260);
                break;
            case "libra":
                jLabel2.setLocation(160, 215);
                break;
            case "escorpiao":
                jLabel2.setLocation(50, 50);
                break;
            case "sagitario":
                jLabel2.setLocation(50, 50);
                break;
            case "capricornio":
                jLabel2.setLocation(50, 50);
                break;
            case "aquario":
                jLabel2.setLocation(50, 50);
                break;
            case "peixes":
                jLabel2.setLocation(50, 50);
                break;
            case "saori":
                jLabel2.setLocation(154, 422);
                break;
            case "acos":
                jLabel2.setLocation(50, 50);
                break;
            case "acos1":
                jLabel2.setLocation(50, 50);
                break;
            case "acos2":
                jLabel2.setLocation(50, 50);
                break;
            case "acos3":
                jLabel2.setLocation(50, 50);
                break;
            case "pratas":
                jLabel2.setLocation(50, 50);
                break;
            case "pratas1":
                jLabel2.setLocation(50, 50);
                break;
            case "pratas2":
                jLabel2.setLocation(50, 50);
                break;
            case "pratas3":
                jLabel2.setLocation(50, 50);
                break;
            case "mestre":
                jLabel2.setLocation(50, 50);
                break;
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 610, 30, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mapa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
